export const GET_ALL_GENRES = "GET_ALL_GENRES";
export const GET_CURRENT_GENRE = "GET_CURRENT_GENRE";
export const ADD_GENRE = "ADD_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";
export const UPDATE_GENRE = "UPDATE_GENRE";
export const TOTAL_GENRES = "TOTAL_GENRE";

export const GET_ALL_MOVIES = "GET_ALL_MOVIES";
export const GET_CURRENT_MOVIE = "GET_CURRENT_MOVIE";
export const ADD_MOVIE = "ADD_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const UPDATE_MOVIE = "UPDATE_MOVIE";
export const TOGGLE_LIKED = "TOGGLE_LIKED";
export const TOTAL_MOVIES = "TOTAL_MOVIES";

export const GET_ALL_CUSTOMERS = "GET_ALL_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";

export const GET_ALL_RENTALS = "GET_ALL_RENTALS";
export const ADD_RENTAL = "ADD_RENTAL";
export const UPDATE_RENTAL = "UPDATE_RENTAL";
export const DELETE_RENTAL = "DELETE_RENTAL";

export const REGISTER_USER = "REGISTER_USER";
export const LOGIN_USER = "LOGIN_USER";
